%% Inicializacion de presentacion
isOpen  = exportToPPTX();
if ~isempty(isOpen)
    % If PowerPoint already started, then close first and then open a new one
    exportToPPTX('close');
end

exportToPPTX('open',fullfile('presentacion','dieTemplate.pptx'));

%% Diapositiva de título
exportToPPTX('addslide','Master',1,'Layout','Diapositiva de título');
exportToPPTX('addtext',{'Modelo SVAR50-4B', sprintf('Corrimiento %s: Libre',MODEL.leg_act)},...
            'Position','Title','fontsize',45);
exportToPPTX('addtext',{'DEPARTAMENTO DE INVESTIGACIONES ECONÓMICAS','BANCO DE GUATEMALA'},...
             'Position','Subtitle','fontsize',20);
exportToPPTX('addtext',sprintf('%s', dat2char(ddtoday)),...
             'Position',[7.00/2.54, 14.45/2.54, 20.75/2.54, 1.05/2.54],...
             'HorizontalAlignment', 'center','fontsize',15);       
         
%% CONTENIDO
exportToPPTX('addslide','Layout','Título y objetos');
exportToPPTX('addtext','CONTENIDO','Position',...
             'Title','fontsize',36,...
             'HorizontalAlignment','Left');
exportToPPTX('addtext',{...         
            sprintf('\t Variables Externas'),...
            sprintf('\t Tipo de Cambio Real'),...
            sprintf('\t Tipo de Cambio Nominal'),...
            sprintf('\t Inflación'),...            
            sprintf('\t Tasa de Interés'),...
            sprintf('\t PIB de Guatemala'),...
            sprintf('\t Base Monetaria'),...
            sprintf('\t Velocidad de Circulación de la Base Monetaria')},...
            'Position','content','fontsize',22);%

%% secciones
VarExt;     
 
%% Guardar y cerrar
exportToPPTX( ...
    'save', ...
    fullfile(sprintf('SVAR50-4B Corrimiento %s', MODEL.CORR_DATE)));
exportToPPTX('close');   


%%
%{

%% REFERENCIA PARA DIAPOSITIVA CON 2 GRÁFICAS
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,MODEL.CORR_VER,... 
                     'PreProcessing','alpha.png'),...
            'Position',[3.25/2.54 0 27.38/2.54 17.55/2.54]); %% Puede variar con el tamaño de la figura?

%% REFERENCIA PARA DIAPOSITIVA CON 2 GRÁFICAS
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,MODEL.CORR_VER,... 
                     'PostProcessing','ln_y_star.png'),...
            'Position',[0 0 16.93/2.54 17.57/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,MODEL.CORR_VER,... 
                     'PostProcessing','ln_y_star.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 17.57/2.54]);  
%% REFERENCIA PARA DIAPOSITIVA CON 3 GRÁFICAS
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,MODEL.CORR_VER,... 
                     'PostProcessing','ln_y_star.png'),...
            'Position',[0 0 16.93/2.54 17.57/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,MODEL.CORR_VER,... 
                     'prediction_compared','d4_ln_y_star.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,MODEL.CORR_VER,... 
                     'prediction_compared','d4_ln_y_star_sm.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);
%}