% isOpen  = exportToPPTX();
% if ~isempty(isOpen)
%     % If PowerPoint already started, then close first and then open a new one
%     exportToPPTX('close');
% end
% 
% exportToPPTX('open',fullfile('presentacion','dieTemplate.pptx'));

%% Encabezado

exportToPPTX('addslide','Layout','Encabezado de sección');
exportToPPTX('addtext','Variables Externas','Position','title','fontsize',48);

%% PIB USA actualizado 
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Producto de Estados Unidos.png'),...
            'Position',[0 0 16.93/2.54 17.57/2.54]); 

% PIB USA actualizado short
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Producto de Estados Unidos_short.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 17.57/2.54]); 
        
%% Simulacion
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','ln_y_star.png'),...
            'Position',[0 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','ln_y_star_gap.png'),...
            'Position',[0 8.78/2.54 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','d4_ln_y_star.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
% exportToPPTX('addpicture',...
%             fullfile('src','presentacion','star.png'),...
%             'Position',[16.93/2.54 0/2.54 0.9/2.54 0.9/2.54]);
                
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','d4_ln_y_star_sm.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);
% simulación short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','ln_y_star_short.png'),...
            'Position',[0 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','ln_y_star_gap_short.png'),...
            'Position',[0 8.78/2.54 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','d4_ln_y_star_short.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
% exportToPPTX('addpicture',...
%             fullfile('src','presentacion','star.png'),...
%             'Position',[16.93/2.54 0/2.54 0.9/2.54 0.9/2.54]);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','d4_ln_y_star_sm_short.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);


%% Indice de precio de las Importaciones USA
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Índice de Precios de Importaciones EEUU.png'),...
            'Position',[0 0 16.93/2.54 17.57/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa intermensual anualizada Precio de Importaciones EEUU.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa de variación interanual Precio de Importaciones EEUU.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);


% Indice de precio de las importaciones USA short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Índice de Precios de Importaciones EEUU_short.png'),...
            'Position',[0 0 16.93/2.54 17.57/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa intermensual anualizada Precio de Importaciones EEUU_short.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa de variación interanual Precio de Importaciones EEUU_short.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);
        
%% Indice de precio de las Exportaciones USA
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Índice de Precios de Exportaciones EEUU.png'),...
            'Position',[0 0 16.93/2.54 17.57/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa intermensual anualizada Precio de exportaciones EEUU.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa de variación interanual Precio de exportaciones EEUU.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);


% Indice de precio de las Exportaciones USA short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Índice de Precios de Exportaciones EEUU_short.png'),...
            'Position',[0 0 16.93/2.54 17.57/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa intermensual anualizada Precio de exportaciones EEUU_short.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa de variación interanual Precio de exportaciones EEUU_short.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);


%% Ponderador ALPHA
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','alpha.png'),...
            'Position',[3.25/2.54 0 27.38/2.54 17.55/2.54]); %% Puede variar con el tamaño de la figura?

% Ponderador ALPHA short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','alpha_short.png'),...
            'Position',[3.25/2.54 0 27.38/2.54 17.55/2.54]); %% Puede variar con el tamaño de la figura?   
        
%% IPEI
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','ln_ipei.png'),...
            'Position',[0 0 16.93/2.54 8.79/2.54]);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','ln_ipei_gap.png'),...
            'Position',[0 8.78/2.54 16.93/2.54 8.79/2.54]);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','dla_ipei.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position',[16.93/2.54 0/2.54 0.9/2.54 0.9/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','d4_ln_ipei.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);

        
%short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','ln_ipei_short.png'),...
            'Position',[0 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','ln_ipei_gap_short.png'),...
            'Position',[0 8.78/2.54 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','dla_ipei_short.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 8.79/2.54]);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position',[16.93/2.54 0/2.54 0.9/2.54 0.9/2.54]);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','d4_ln_ipei_short.png'),...
            'Position',[16.93/2.54 8.78/2.54 16.93/2.54 8.79/2.54]);

        
%% TASA DE INTERÉS EXTERNA
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','i_star.png'),... 
            'Position',[0 0 16.93/2.54 17.57/2.54]);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position',[0/2.54 0/2.54 0.9/2.54 0.9/2.54]);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa de fondos federales.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 17.57/2.54]);  
% short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','i_star_short.png'),... 
            'Position',[0 0 16.93/2.54 17.57/2.54]);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position',[0/2.54 0/2.54 0.9/2.54 0.9/2.54]);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','Tasa de fondos federales_short.png'),...
            'Position',[16.93/2.54 0 16.93/2.54 17.57/2.54]);  
%%
% exportToPPTX( ...
%     'save', ...
%     'prueba');
% exportToPPTX('close');  