%% Escenarios Alternos
%{
    Escenarios de riesgo alrededor de variables externas o que no son
    instrumentos de Política Monetaria.

    Se "endogeniza" el choque propio de las variables ancladas.
%}

%% 1. JCCF: Anclaje de IPEI proveniente de QPM en horizonte de pronóstico
% (8 Trimestres)

% Base de datos
alt1 = databank.fromCSV(...
        fullfile('data', 'corrimientos',MODEL.CORR_DATE,...
                 'v1', 'fulldata_QPM.csv')); 
             
% Trimestres de anclaje
MODEL.DATES.E1_dates = MODEL.DATES.pred_start:MODEL.DATES.pred_start+7;

%% %%%%%%%%%%%%%%%% Creación de escenario alternativo %%%%%%%%%%%%%%%%%%%%%%
% Shocks del escenario base
shocks = MODEL.F_pred*get(MODEL.MF, 'elist');
% Concatenación de bd con condiciones iniciales (MODEL.F) y shocks Esc.
% Libre
MODEL.Alt1.dbi = dboverlay(MODEL.F,shocks);

% Imposición de anclajes provenientes del QPM en base de datos
MODEL.Alt1.dbi.d4_ln_ipei(MODEL.DATES.E1_dates) = alt1.D4L_CPI_RW(MODEL.DATES.E1_dates);

% Plan de simulación
MODEL.Alt1.planSim = plan(MODEL.MF,MODEL.DATES.pred_start:MODEL.DATES.pred_end);
% Variable a endogenizar (shock propio?? No necesariamente)
MODEL.Alt1.planSim = endogenize(MODEL.Alt1.planSim,{'s_d4_ln_ipei'},MODEL.DATES.E1_dates); 
% Variable a exogenizar (Anclaje)
MODEL.Alt1.planSim = exogenize(MODEL.Alt1.planSim,{'d4_ln_ipei'},MODEL.DATES.E1_dates);

% Simulación.
MODEL.Alt1.pred = simulate(MODEL.MF,...
                  MODEL.Alt1.dbi,...
                  MODEL.DATES.pred_start:MODEL.DATES.pred_end,...
                  'plan',MODEL.Alt1.planSim,...
                  'anticipate',false,...
                  'DbOverlay=', true);
% Descomposición             
MODEL.Alt1.shd = simulate(MODEL.MF,...
                  MODEL.Alt1.pred,...
                  MODEL.DATES.hist_start:MODEL.DATES.pred_end,...
                  'anticipate',false,...
                  'contributions',true);
             
%% Post Procesamiento
MODEL = PostProcessing(MODEL,...
                       'list',pp_list,...
                       'list_niv', list_nivel,...
                       'Esc',{'v1', MODEL.Alt1.pred});

%% GRÁFICAS
% Preprocessing
PreProcPlots(MODEL,...
             'Esc_add', {'v1', MODEL_ANT},...
             'tab_range', tab_range_source_data,...
             'tab_range_mm', tab_range_mm);

% Variables del modelo
simPlots(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','prediction_compared'),...}
         'Esc_add', {'v1', MODEL.Alt1.pred},...
         'PlotList', get(MODEL.MF, 'xlist'),...
         'LegendsNames',{'Anclaje IPEI', 'Escenario Libre'},...
         'TabRange', tab_range...
         );
% Postprocesamiento - Logaritmos desestacionalizados y tendencia
PostPrLogs(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v1', 'PostProcessing'),...
         'Esc',{'v1', MODEL.Alt1.pred},...
         'PlotList', pp_list,...
         'LegendsNames',{'Tendencia (HP, Lambda=1600)', 'Logaritmo (SA, X12)'},...
         'TabRange', tab_range...
         );     
% Postprocesamiento - Niveles
PostPrLevels(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','PostProcessing'),...
         'Esc_add', {'v1', MODEL.PostProc.v1},...
         'PlotList', list_lev,...
         'Titles', tit_lev,...
         'LegendsNames',{'Anclaje IPEI', 'Escenario Libre'},...
         'TabRange', tab_range...
         ); 
% Postprocesamiento - Brechas
PostPrGaps(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','PostProcessing'),...
         'Esc_add', {'v1', MODEL.PostProc.v1},...
         'PlotList', list_gaps,...
         'LegendsNames',{'Anclaje IPEI', 'Escenario Libre'},...
         'TabRange', tab_range...
         ); 

% Tipo de cambio real
    % Componentes Tipo de cambio real
    tc_real(MODEL,...
        'Esc_add', {'v1', MODEL.Alt1.pred},...
        'tab_range', tab_range,...
        'LegendsNames',{'Anclaje IPEI', 'Escenario Libre'});
    
    % Subplot tcr
    tcr_subplot(MODEL,...
        'Esc_add', {'v1', MODEL.PostProc},...
        'tab_range', tab_range,...
        'LegendsNames',{'Escenario Libre', 'Anclaje IPEI'})

% Componentes Velocidad de Circulación de la Base Monetaria
velocidad_subplot(MODEL,...
                  'tab_range', tab_range,...
                  'Esc_add', {'v1', MODEL.PostProc},...
                  'LegendsNames',{'Escenario Libre', 'Anclaje IPEI'},...     
                  'tab_range', tab_range);

% Descomposición de shocks
% Rango completo
plot_shd_dsc(MODEL, MODEL.Alt1.pred, MODEL.Alt1.shd,...
            'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','Shock_dec\long'),...
            'Rng', {},...
            'Variables',list)
        
% Rango corto
plot_shd_dsc(MODEL, MODEL.Alt1.pred,MODEL.Alt1.shd,...
             'SavePath', fullfile('plots',MODEL.CORR_DATE,'v1','Shock_dec\short'),...
             'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
             'Variables',list); 
              