%% Escenario Combinado
%{
    Se combina el escenario alterno 1 y el contrafactual de política 1

%}

%% 1. JCCF: Anclaje de IPEI proveniente de QPM en horizonte de pronóstico
% (8 Trimestres)

% Base de datos
alt1 = databank.fromCSV(...
        fullfile('data', 'corrimientos',MODEL.CORR_DATE,...
                 'v1', 'fulldata_QPM.csv')); 
             
% Trimestres de anclaje
MODEL.DATES.E1_dates = MODEL.DATES.pred_start:MODEL.DATES.pred_start+7;

%% %%%%%%%%%%%%%%%% Creación de escenario alternativo %%%%%%%%%%%%%%%%%%%%%%
% Shocks del escenario base
shocks = MODEL.F_pred*get(MODEL.MF, 'elist');
% Concatenación de bd con condiciones iniciales (MODEL.F) y shocks Esc.
% Libre
MODEL.Comb1.dbi = dboverlay(MODEL.F,shocks);

% Imposición de anclajes provenientes del QPM en base de datos
MODEL.Comb1.dbi.d4_ln_ipei(MODEL.DATES.E1_dates) = alt1.D4L_CPI_RW(MODEL.DATES.E1_dates);
MODEL.Comb1.dbi.i(MODEL.DATES.pred_start) = MODEL.F.i(MODEL.DATES.hist_end);


% Plan de simulación
MODEL.Comb1.planSim = plan(MODEL.MF,MODEL.DATES.pred_start:MODEL.DATES.pred_end);
% Variable a endogenizar (shock propio?? No necesariamente)
MODEL.Comb1.planSim = endogenize(MODEL.Comb1.planSim,{'s_d4_ln_ipei'},MODEL.DATES.E1_dates); 
MODEL.Comb1.planSim = endogenize(MODEL.CP1.planSim,{'s_i'},MODEL.DATES.pred_start); 
% Variable a exogenizar (Anclaje)
MODEL.Comb1.planSim = exogenize(MODEL.Comb1.planSim,{'d4_ln_ipei'},MODEL.DATES.E1_dates);
MODEL.Comb1.planSim = exogenize(MODEL.CP1.planSim,{'i'},MODEL.DATES.pred_start);

% Simulación.

MODEL.Comb1.pred = simulate(MODEL.MF,...
                  MODEL.Comb1.dbi,...
                  MODEL.DATES.pred_start:MODEL.DATES.pred_end,...
                  'plan',MODEL.Comb1.planSim,...
                  'anticipate',false,...
                  'DbOverlay=', true);
              
%% Post Procesamiento
MODEL = PostProcessing(MODEL,...
                       'list',pp_list,...
                       'list_niv', list_nivel,...
                       'Esc',{'v3', MODEL.Comb1.pred});
          
%% GRÁFICAS

% Variables del modelo
simPlots(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v3','prediction_compared'),...}
         'Esc_add', {'v3', MODEL.Comb1.pred},...
         'PlotList', get(MODEL.MF, 'xlist'),...
         'LegendsNames',{'Esc. Combinado', 'Escenario Libre'},...
         'TabRange', tab_range...
         );
% Postprocesamiento - Logaritmos desestacionalizados y tendencia
PostPrLogs(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v3', 'PostProcessing'),...
         'Esc',{'v3', MODEL.Comb1.pred},...
         'PlotList', pp_list,...
         'LegendsNames',{'Tendencia (HP, Lambda=1600)', 'Logaritmo (SA, X12)'},...
         'TabRange', tab_range...
         );     
% Postprocesamiento - Niveles
PostPrLevels(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v3','PostProcessing'),...
         'Esc_add', {'v3', MODEL.PostProc.v3},...
         'PlotList', list_lev,...
         'Titles', tit_lev,...
         'LegendsNames',{'Esc. Combinado', 'Escenario Libre'},...
         'TabRange', tab_range...
         ); 
% Postprocesamiento - Brechas
PostPrGaps(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v3','PostProcessing'),...
         'Esc_add', {'v3', MODEL.PostProc.v3},...
         'PlotList', list_gaps,...
         'LegendsNames',{'Esc. Combinado', 'Escenario Libre'},...
         'TabRange', tab_range...
         ); 
     