%% Contrafactual de PM

%{
    Escenarios contrafactuales utilizando instrumentos de PM:
                - Tasa de interes líder
                - Base Monetaria

    No necesariamente se "endogeniza" el choque correspondiente a la
    variable anclada, ni en los mismos períodos.
%}


%% Tasa de interés invariable en el primer trimestre de pronóstico

shocks = MODEL.F_pred*get(MODEL.MF, 'elist');
MODEL.CP1.dbi = dboverlay(MODEL.F,shocks);
% Mantener la tasa invariable
MODEL.CP1.dbi.i(MODEL.DATES.pred_start) = MODEL.F.i(MODEL.DATES.hist_end);

% Plan de simulación
MODEL.CP1.planSim = plan(MODEL.MF,MODEL.DATES.pred_start:MODEL.DATES.pred_end);
% Variable a endogenizar (shock propio?? No necesariamente)
MODEL.CP1.planSim = endogenize(MODEL.CP1.planSim,{'s_i'},MODEL.DATES.pred_start); 
% Variable a exogenizar (Anclaje)
MODEL.CP1.planSim = exogenize(MODEL.CP1.planSim,{'i'},MODEL.DATES.pred_start);

% Simulación.
MODEL.CP1.pred = simulate(MODEL.MF,...
              MODEL.CP1.dbi,...
              MODEL.DATES.pred_start:MODEL.DATES.pred_end,...
              'plan',MODEL.CP1.planSim,...
              'anticipate',false,...
              'DbOverlay=', true);

%% Post Procesamiento
MODEL = PostProcessing(MODEL,...
                       'list',pp_list,...
                       'list_niv', list_nivel,...
                       'Esc',{'v2', MODEL.CP1.pred});
          
%% GRÁFICAS

% Variables del modelo
simPlots(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v2','prediction_compared'),...}
         'Esc_add', {'v2', MODEL.CP1.pred},...
         'PlotList', get(MODEL.MF, 'xlist'),...
         'LegendsNames',{'Contrafactual 1', 'Escenario Libre'},...
         'TabRange', tab_range...
         );
% Postprocesamiento - Logaritmos desestacionalizados y tendencia
PostPrLogs(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v2', 'PostProcessing'),...
         'Esc',{'v2', MODEL.CP1.pred},...
         'PlotList', pp_list,...
         'LegendsNames',{'Tendencia (HP, Lambda=1600)', 'Logaritmo (SA, X12)'},...
         'TabRange', tab_range...
         );     
% Postprocesamiento - Niveles
PostPrLevels(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v2','PostProcessing'),...
         'Esc_add', {'v2', MODEL.PostProc.v2},...
         'PlotList', list_lev,...
         'Titles', tit_lev,...
         'LegendsNames',{'Contrafactual 1', 'Escenario Libre'},...
         'TabRange', tab_range...
         ); 
% Postprocesamiento - Brechas
PostPrGaps(MODEL,...
         'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
         'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
         'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v2','PostProcessing'),...
         'Esc_add', {'v2', MODEL.PostProc.v2},...
         'PlotList', list_gaps,...
         'LegendsNames',{'Contrafactual 1', 'Escenario Libre'},...
         'TabRange', tab_range...
         ); 
     