%% Escenario Combinado
%{
    Se combina el escenario alterno 1 y el contrafactual de política 1

%}

%% 1. JCCF: Anclaje de IPEI proveniente de QPM en horizonte de pronóstico
% (8 Trimestres)

% Base de datos
alt1 = databank.fromCSV(...
        fullfile('data', 'corrimientos',MODEL.CORR_DATE,...
                 'v1', 'fulldata_QPM.csv')); 
             
% Trimestres de anclaje
MODEL.DATES.E1_dates = MODEL.DATES.pred_start:MODEL.DATES.pred_start+7;

%% %%%%%%%%%%%%%%%% Creación de escenario alternativo %%%%%%%%%%%%%%%%%%%%%%
% Shocks del escenario base
shocks = MODEL.F_pred*get(MODEL.MF, 'elist');
% Concatenación de bd con condiciones iniciales (MODEL.F) y shocks Esc.
% Libre
MODEL.Esc.v3.dbi = dboverlay(MODEL.F,shocks);

% Imposición de anclajes provenientes del QPM en base de datos
MODEL.Esc.v3.dbi.d4_ln_ipei(MODEL.DATES.E1_dates) = alt1.D4L_CPI_RW(MODEL.DATES.E1_dates);
MODEL.Esc.v3.dbi.i(MODEL.DATES.pred_start) = MODEL.F.i(MODEL.DATES.hist_end);


% Plan de simulación
MODEL.Esc.v3.planSim = plan(MODEL.MF,MODEL.DATES.pred_start:MODEL.DATES.pred_end);
% Variable a endogenizar (shock propio?? No necesariamente)
MODEL.Esc.v3.planSim = endogenize(MODEL.Esc.v3.planSim,{'s_d4_ln_ipei'},MODEL.DATES.E1_dates); 
MODEL.Esc.v3.planSim = endogenize(MODEL.Esc.v3.planSim,{'s_i'},MODEL.DATES.pred_start); 
% Variable a exogenizar (Anclaje)
MODEL.Esc.v3.planSim = exogenize(MODEL.Esc.v3.planSim,{'d4_ln_ipei'},MODEL.DATES.E1_dates);
MODEL.Esc.v3.planSim = exogenize(MODEL.Esc.v3.planSim,{'i'},MODEL.DATES.pred_start);

% Simulación.

MODEL.Esc.v3.pred = simulate(MODEL.MF,...
                  MODEL.Esc.v3.dbi,...
                  MODEL.DATES.pred_start:MODEL.DATES.pred_end,...
                  'plan',MODEL.Esc.v3.planSim,...
                  'anticipate',false,...
                  'DbOverlay=', true);
              
% Descomposición             
MODEL.Esc.v3.shd = simulate(MODEL.MF,...
                  MODEL.Esc.v3.pred,...
                  MODEL.DATES.hist_start:MODEL.DATES.pred_end,...
                  'anticipate',false,...
                  'contributions',true);  
              
%% Post Procesamiento
MODEL = PostProcessing(MODEL,...
                       'list',pp_list,...
                       'list_niv', list_nivel,...
                       'Esc',{'v3', MODEL.Esc.v3.pred});
          
%% GRÁFICAS
if do_graphs == true
    % Preprocessing
    PreProcPlots(MODEL,...
        'Esc_add', {'v3', MODEL_ANT},...
        'tab_range', tab_range_source_data,...
        'tab_range_mm', tab_range_mm);
    
    % Variables del modelo
    simPlots(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v3','prediction_compared'),...}
        'Esc_add', {'v3', MODEL.Esc.v3.pred, MODEL.esc_col{3}},...
        'PlotList', get(MODEL.MF, 'xlist'),...
        'LegendsNames',{MODEL.esc_names{4}, MODEL.esc_names{1}},...
        'TabRange', tab_range...
        );
    % Postprocesamiento - Logaritmos desestacionalizados y tendencia
    PostPrLogsComp(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v3', 'PostProcessing'),...
        'Esc',{'v0', MODEL.PostProc},...
        'Esc_add', {'v3', MODEL.PostProc.v3, MODEL.esc_col{3}},...
        'PlotList', pp_list,...
        'LegendsNames',{MODEL.esc_names{4}, MODEL.esc_names{1}},...
        'TabRange', tab_range...
        );
    % Postprocesamiento - Niveles
    PostPrLevels(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v3','PostProcessing'),...
        'Esc_add', {'v3', MODEL.PostProc.v3, MODEL.esc_col{3}},...
        'PlotList', list_lev,...
        'Titles', tit_lev,...
        'LegendsNames',{MODEL.esc_names{4}, MODEL.esc_names{1}},...
        'TabRange', tab_range...
        );
    % Postprocesamiento - Brechas
    PostPrGaps(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v3','PostProcessing'),...
        'Esc_add', {'v3', MODEL.PostProc.v3, MODEL.esc_col{3}},...
        'PlotList', list_gaps,...
        'LegendsNames',{MODEL.esc_names{4}, MODEL.esc_names{1}},...
        'TabRange', tab_range...
        );
    
    
    % Tipo de cambio real
    % Componentes Tipo de cambio real
    tc_real(MODEL,...
        'Esc_add', {'v3', MODEL.Esc.v3.pred},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{4}, MODEL.esc_names{1}});
    
    % Subplot tcr
    tcr_subplot(MODEL,...
        'Esc_add', {'v3', MODEL.PostProc, MODEL.esc_col{3}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{4}, MODEL.esc_names{1}});
    
    % Componentes Velocidad de Circulación de la Base Monetaria
    velocidad_subplot(MODEL,...
        'tab_range', tab_range,...
        'Esc_add', {'v3', MODEL.PostProc, MODEL.esc_col{3}},...
        'LegendsNames',{MODEL.esc_names{4}, MODEL.esc_names{1}},...
        'tab_range', tab_range);
    
    % Descomposición de shocks
    % Rango completo
    list = [MODEL.ExoVar(4:end), 'd4_ln_cpi', 'd4_ln_z', 'd4_ln_v', 'r'];
    plot_shd_dsc(MODEL, MODEL.Esc.v3.pred, MODEL.Esc.v3.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v3','Shock_dec\long'),...
        'Rng', {},...
        'Variables',list)
    
    % Rango corto
    plot_shd_dsc(MODEL, MODEL.Esc.v3.pred, MODEL.Esc.v3.shd,...
        'SavePath', fullfile('plots',MODEL.CORR_DATE,'v3','Shock_dec\short'),...
        'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
        'Variables',list);
    
    % Primera diferencia de la descomposicón de shocks
    % Rango corto
    plot_diff_shd_dsc(MODEL, MODEL.Esc.v3.pred, MODEL.Esc.v3.shd,...
                                       'SavePath', fullfile('plots',MODEL.CORR_DATE,'v3','Shock_dec\diff'),...
                                       'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
                                       'Variables', list);
    
    % Graficas de contribuciones
    contributions(MODEL,...
                  'SavePath',fullfile('plots', MODEL.CORR_DATE, 'v3', 'contributions'),...
                  'Esc_add', {'v3', MODEL.Esc.v3.pred});
              
    contributions(MODEL,...
                  'SavePath',fullfile('plots', MODEL.CORR_DATE, 'v3', 'diff contributions'),...
                  'Esc_add', {'v3', MODEL.Esc.v3.pred},...
                  'diff', true);
                                   
end
disp('Escenario 3: ok');