%{
Graficas con los datos fuente
    - Producto externo

%}
%% Producto externo

        set( ...
        gcf, ...
        'defaultaxesfontsize',12, ...
        'Position', [1 42.0182 1417.1 976.73] ...
    );
    
    main_p = uipanel('Units','normalized');
    
    % ----- Panel de gráfica -----
    plot_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8, 1, 0.8], ...
        'BackgroundColor', [1, 1, 1] ...
    );

    ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);
            
    % panel
        table_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
        'BackgroundColor', [1, 1, 1] ...
    );
    
    data_table = [];
        data_table(:, 1) = MODEL.PreProc.quarterly.y_star_qq(tab_range-9);

        text_Color = [[0 0 1]];


    SimTools.scripts.plot_data_table( ...
        tab_range-9, ...
        data_table, ...
        'Parent', table_p, ...
        'SeriesNames', {'Produto de EEUU'}, ...
        'TextColor', text_Color, ...
        'ColNameWidth', 0.23, ...
        'FontSize', 11 ...
    )
       
    axis on
                                
       plt = plot(MODEL.PreProc.quarterly.y_star_qq, ...
            'Marker', '.', ...
            'MarkerSize', 17, ...
            'LineWidth', 1.25, ...
            'color', [0,0,1]);  
            
      %Titulos
    title('Producto de Estados Unidos',...
        {'Miles de Millones US$', 'Encadenados 2017'})      
            
SimTools.scripts.pausaGuarda(...
fullfile('plots',... 
         'corrimiento', ...
          MODEL.CORR_DATE, MODEL.CORR_VER,...
          'PreProcessing',...
          'Producto EEUU.png'), ...
'AutoSave', true) 

%% Precios de importados
% trimestralización y diferencia trimestral anualizada precios de
% importados
MODEL.PreProc.quarterly.imp_indx_qq = convert(MODEL.PreProc.monthly.imp_indx_mm, 'Q', 'method=', @mean);
% Variación Interanual
MODEL.PreProc.monthly.imp_indx_dif12_mm = MODEL.PreProc.monthly.imp_indx_mm.diff(-12);

MODEL.PreProc.monthly.imp_indx_mm.Comment = 'Precios de Importaciones EEUU';
MODEL.PreProc.monthly.imp_indx_dif12_mm.Comment = 'Tasa de variación interanual Precio de Importaciones EEUU';
MODEL.PreProc.quarterly.imp_indx_qq.Comment = 'Tasa intertrimestral anualizada Precio de Importaciones EEUU';
% variables a graficar
toplot = {'imp_indx_mm', 'imp_indx_dif12_mm'};

for i = 1:length(toplot)
    % Precios de importados en niveles
            set( ...
            gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1417.1 976.73] ...
        );

        main_p = uipanel('Units','normalized');

        % ----- Panel de gráfica -----
        plot_p = uipanel( ...
            main_p, ...
            'Position', [0, 1 - 0.8, 1, 0.8], ...
            'BackgroundColor', [1, 1, 1] ...
        );

        ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

        % panel
            table_p = uipanel( ...
            main_p, ...
            'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
            'BackgroundColor', [1, 1, 1] ...
        );

        data_table = [];
            data_table(:, 1) = MODEL.PreProc.monthly.(toplot{i})(tab_range_mm);

            text_Color = [[0 0 1]];

        if i == 1
        SimTools.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Precios de importados'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
        )
        
        else
                SimTools.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Tasa de variación interanual'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
        )
            
            
        end
    
        axis on

            plot(MODEL.PreProc.monthly.(toplot{i}), ...
                'Marker', '.', ...
                'MarkerSize', 17, ...
                'LineWidth', 1.25, ...
                'color', [0,0,1]);  

          %Titulos
        title(MODEL.PreProc.monthly.(toplot{i}).Comment{1})      

    SimTools.scripts.pausaGuarda(...
    fullfile('plots',... 
         'corrimiento', ...
          MODEL.CORR_DATE, MODEL.CORR_VER,...
          'PreProcessing',...
          sprintf("%s.png",MODEL.PreProc.monthly.(toplot{i}).Comment{1})), ...
    'AutoSave', true) 
end

% tasa de intertrimestral anualizada
            set( ...
            gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1417.1 976.73] ...
        );

        main_p = uipanel('Units','normalized');

        % ----- Panel de gráfica -----
        plot_p = uipanel( ...
            main_p, ...
            'Position', [0, 1 - 0.8, 1, 0.8], ...
            'BackgroundColor', [1, 1, 1] ...
        );

        ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

        % panel
            table_p = uipanel( ...
            main_p, ...
            'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
            'BackgroundColor', [1, 1, 1] ...
        );

        data_table = [];
            data_table(:, 1) = MODEL.PreProc.quarterly.imp_indx_qq(tab_range-9);

            text_Color = [[0 0 1]];


        SimTools.scripts.plot_data_table( ...
            tab_range-9, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Tasa de variación intertrimestral'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
        )

        axis on

           plt = plot(MODEL.PreProc.quarterly.imp_indx_qq, ...
                'Marker', '.', ...
                'MarkerSize', 17, ...
                'LineWidth', 1.25, ...
                'color', [0,0,1]);  

          %Titulos
        title(MODEL.PreProc.quarterly.imp_indx_qq.Comment{1})      

    SimTools.scripts.pausaGuarda(...
    fullfile('plots',... 
          'corrimiento', ...
          MODEL.CORR_DATE, MODEL.CORR_VER,...
          'PreProcessing',...
          sprintf("%s.png",MODEL.PreProc.quarterly.imp_indx_qq.Comment{1})), ...
    'AutoSave', true) 

%% Precio de exportaciones
% trimestralización y diferencia trimestral anualizada precios de
% exportaciones
MODEL.PreProc.quarterly.exp_indx_qq = convert(MODEL.PreProc.monthly.exp_indx_mm, 'Q', 'method=', @mean);
% Variación Interanual
MODEL.PreProc.monthly.exp_indx_dif12_mm = MODEL.PreProc.monthly.exp_indx_mm.diff(-12);

MODEL.PreProc.monthly.exp_indx_mm.Comment = 'Precios de exportaciones EEUU';
MODEL.PreProc.monthly.exp_indx_dif12_mm.Comment = 'Tasa de variación interanual Precio de exportaciones EEUU';
MODEL.PreProc.quarterly.exp_indx_qq.Comment = 'Tasa intertrimestral anualizada Precio de exportaciones EEUU';
% variables a graficar
toplot = {'exp_indx_mm', 'exp_indx_dif12_mm'};

for i = 1:length(toplot)
    % Precios de importados en niveles
            set( ...
            gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1417.1 976.73] ...
        );

        main_p = uipanel('Units','normalized');

        % ----- Panel de gráfica -----
        plot_p = uipanel( ...
            main_p, ...
            'Position', [0, 1 - 0.8, 1, 0.8], ...
            'BackgroundColor', [1, 1, 1] ...
        );

        ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

        % panel
            table_p = uipanel( ...
            main_p, ...
            'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
            'BackgroundColor', [1, 1, 1] ...
        );

        data_table = [];
            data_table(:, 1) = MODEL.PreProc.monthly.(toplot{i})(tab_range_mm);

            text_Color = [[0 0 1]];

        if i == 1
        SimTools.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Precios de importados'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
        )
        
        else
                SimTools.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Tasa de variación interanual'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
        )
            
            
        end
    
        axis on

            plot(MODEL.PreProc.monthly.(toplot{i}), ...
                'Marker', '.', ...
                'MarkerSize', 17, ...
                'LineWidth', 1.25, ...
                'color', [0,0,1]);  

          %Titulos
        title(MODEL.PreProc.monthly.(toplot{i}).Comment{1})      

    SimTools.scripts.pausaGuarda(...
    fullfile('plots',... 
          'corrimiento', ...
          MODEL.CORR_DATE, MODEL.CORR_VER,...
          'PreProcessing',...
          sprintf("%s.png",MODEL.PreProc.monthly.(toplot{i}).Comment{1})), ...
    'AutoSave', true) 
end

% tasa de intertrimestral anualizada
            set( ...
            gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1417.1 976.73] ...
        );

        main_p = uipanel('Units','normalized');

        % ----- Panel de gráfica -----
        plot_p = uipanel( ...
            main_p, ...
            'Position', [0, 1 - 0.8, 1, 0.8], ...
            'BackgroundColor', [1, 1, 1] ...
        );

        ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

        % panel
            table_p = uipanel( ...
            main_p, ...
            'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
            'BackgroundColor', [1, 1, 1] ...
        );

        data_table = [];
            data_table(:, 1) = MODEL.PreProc.quarterly.exp_indx_qq(tab_range-9);

            text_Color = [[0 0 1]];


        SimTools.scripts.plot_data_table( ...
            tab_range-9, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Tasa de variación intertrimestral'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
        )

        axis on

           plt = plot(MODEL.PreProc.quarterly.exp_indx_qq, ...
                'Marker', '.', ...
                'MarkerSize', 17, ...
                'LineWidth', 1.25, ...
                'color', [0,0,1]);  

          %Titulos
        title(MODEL.PreProc.quarterly.exp_indx_qq.Comment{1})      

    SimTools.scripts.pausaGuarda(...
    fullfile('plots',... 
          'corrimiento', ...
          MODEL.CORR_DATE, MODEL.CORR_VER,...
          'PreProcessing',...
          sprintf("%s.png",MODEL.PreProc.quarterly.exp_indx_qq.Comment{1})), ...
    'AutoSave', true)

%% Evolución alpha
        set( ...
        gcf, ...
        'defaultaxesfontsize',12, ...
        'Position', [1 42.0182 1117.1 776.73] ...
    );
    

    main_p = uipanel('Units','normalized');
    
    % ----- Panel de gráfica -----
    plot_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8, 1, 0.8], ...
        'BackgroundColor', [1, 1, 1] ...
    );

    ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);


    plt = plot(MODEL.DATES.hist_start_mm:MODEL.DATES.hist_end_mm,...
               [MODEL.PreProc.monthly.a_mm, MODEL.PreProc.monthly.a_prom_mm], ...
            'LineWidth', 1.25 ...
            );

    % Colores
    % mes con mes
    set(plt(1), 'color', [0 0 0], 'LineWidth', 1.25);
    % promedio movil 12 meses
    set(plt(2), 'color', [0 0.498 0],'LineWidth', 1.25, 'Marker', '.', 'MarkerSize', 12);
    
    % leyenda
    legend({'Evolución mensual', 'Promedio Movil (12 meses)'}, 'Location','best');
    
    %Titulos
    title('Importancia de EEUU en importaciones de GT')
      
    % panel
        table_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
        'BackgroundColor', [1, 1, 1] ...
    );
    
    data_table = [];
        data_table(:, 1) = MODEL.PreProc.monthly.a_mm(tab_range_mm);
        data_table(:, 2) = MODEL.PreProc.monthly.a_prom_mm(tab_range_mm);       
        text_Color = [[0 0 0]; [0 0.498 0]];


    SimTools.scripts.plot_data_table( ...
        tab_range_mm, ...
        data_table, ...
        'Parent', table_p, ...
        'SeriesNames', {'Evolución mensual', 'Promedio Movil 12 meses'}, ...
        'TextColor', text_Color, ...
        'ColNameWidth', 0.23, ...
        'FontSize', 11 ...
    )
       
    axis on
      
   SimTools.scripts.pausaGuarda(...
    fullfile('plots',... 
          'corrimiento', ...
          MODEL.CORR_DATE, MODEL.CORR_VER,...
          'PreProcessing',...
          'alpha.png'), ...
    'AutoSave', true);
