%{
Graficas con los datos fuente
    - Producto externo
%}

MODEL.PreProc.monthly_temp = dbclip(MODEL.PreProc.monthly, MODEL.PreProc.monthly.a_prom_mm.End-60,...
    MODEL.PreProc.monthly.a_prom_mm.End);

MODEL.PreProc.quarterly_temp = dbclip(MODEL.PreProc.quarterly, MODEL.PreProc.quarterly.y_star_qq.End-20,...
    MODEL.PreProc.quarterly.y_star_qq.End);

%% Producto y tasa de fondos federales
toplot = {'y_star_qq', 'y_qq','i_star_mm'};

for i = 1:length(toplot)
    
    figure;
    set( ...
        gcf, ...
        'defaultaxesfontsize',12, ...
        'Position', [1 42.0182 1417.1 976.73] ...
        );
    
    main_p = uipanel('Units','normalized');
    
    % ----- Panel de gráfica -----
    plot_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8, 1, 0.8], ...
        'BackgroundColor', [1, 1, 1] ...
        );
    
    ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);
    
    % panel
    table_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
        'BackgroundColor', [1, 1, 1] ...
        );
    
    if strcmp(toplot{i}, 'y_star_qq') || strcmp(toplot{i}, 'y_qq')
        
        data_table = [];
        data_table(:, 1) = MODEL.PreProc.quarterly_temp.(toplot{i})(tab_range-12);
        
        text_Color = [[0 0 1]];
        
        
        Sim.scripts.plot_data_table( ...
            tab_range-12, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {MODEL.PreProc.quarterly.(toplot{i}).Comment{1}}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 11 ...
            );
        
        axis on
        
        plt = plot(MODEL.PreProc.quarterly_temp.y_star_qq.range,...
            MODEL.PreProc.quarterly_temp.(toplot{i}), ...
            'Marker', '.', ...
            'MarkerSize', 17, ...
            'LineWidth', 1.25, ...
            'color', [0,0,1]);
        ax = gca;
        ax.YAxis.Exponent = 0;
        
        %Titulos
        title(MODEL.PreProc.quarterly_temp.(toplot{i}).Comment{1},...
            strcat(dat2char(MODEL.PreProc.quarterly_temp.y_star_qq.Start),...
            '-',dat2char(MODEL.PreProc.quarterly_temp.y_star_qq.End)));
        
        
        Sim.scripts.pausaGuarda(fullfile(SavePath,sprintf("%s_short.png",MODEL.PreProc.quarterly_temp.(toplot{i}).Comment{1})),...
            'AutoSave', true);
        
        
        
    else
        
        data_table = [];
        data_table(:, 1) = MODEL.PreProc.monthly_temp.(toplot{i})(tab_range_mm);
        
        text_Color = [[0 0 1]];
        
        
        Sim.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Tasa de interés externa'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 11 ...
            );
        
        axis on
        
        plt = plot(MODEL.PreProc.monthly_temp.(toplot{i}), ...
            'Marker', '.', ...
            'MarkerSize', 17, ...
            'LineWidth', 1.25, ...
            'color', [0,0,1]);
        
        %Titulos
        title('Tasa de interés de Fondos Federales',...
            strcat(dat2char(MODEL.PreProc.monthly_temp.i_star_mm.Start),...
            '-',dat2char(MODEL.PreProc.monthly_temp.i_star_mm.End)));
        
        
        Sim.scripts.pausaGuarda(fullfile(SavePath,'Tasa de fondos federales_short.png'),...
            'AutoSave', true);
        
    end
end


%% Precios de importados
toplot = {'imp_indx_mm', 'imp_indx_dif12_mm'};
for i = 1:length(toplot)
    % Precios de importados en niveles
    set( ...
        gcf, ...
        'defaultaxesfontsize',12, ...
        'Position', [1 42.0182 1417.1 976.73] ...
        );
    
    main_p = uipanel('Units','normalized');
    
    % ----- Panel de gráfica -----
    plot_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8, 1, 0.8], ...
        'BackgroundColor', [1, 1, 1] ...
        );
    
    ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);
    
    % panel
    table_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
        'BackgroundColor', [1, 1, 1] ...
        );
    
    data_table = [];
    data_table(:, 1) = MODEL.PreProc.monthly_temp.(toplot{i})(tab_range_mm);
    
    text_Color = [[0 0 1]];
    
    if i == 1
        Sim.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Índice de Precios de importados'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
            );
        
    else
        Sim.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Tasa de variación interanual'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
            );
        
        
    end
    
    axis on
    
    plot(MODEL.PreProc.monthly_temp.(toplot{i}), ...
        'Marker', '.', ...
        'MarkerSize', 17, ...
        'LineWidth', 1.25, ...
        'color', [0,0,1]);
    
    %Titulos
    title(MODEL.PreProc.monthly_temp.(toplot{i}).Comment{1},...
        strcat(dat2char(MODEL.PreProc.monthly_temp.(toplot{i}).Start),...
        '-',dat2char(MODEL.PreProc.monthly_temp.(toplot{i}).End)))
    
    Sim.scripts.pausaGuarda(...
        fullfile(SavePath,...
        sprintf("%s_short.png",MODEL.PreProc.monthly_temp.(toplot{i}).Comment{1})), ...
        'AutoSave', true);
end

% tasa de intertrimestral anualizada
set( ...
    gcf, ...
    'defaultaxesfontsize',12, ...
    'Position', [1 42.0182 1417.1 976.73] ...
    );

main_p = uipanel('Units','normalized');

% ----- Panel de gráfica -----
plot_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8, 1, 0.8], ...
    'BackgroundColor', [1, 1, 1] ...
    );

ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

% panel
table_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
    'BackgroundColor', [1, 1, 1] ...
    );

data_table = [];
data_table(:, 1) = MODEL.PreProc.quarterly_temp.imp_indx_dif1_qq(tab_range-12);

text_Color = [[0 0 1]];


Sim.scripts.plot_data_table( ...
    tab_range-12, ...
    data_table, ...
    'Parent', table_p, ...
    'SeriesNames', {'Tasa de variación intertrimestral'}, ...
    'TextColor', text_Color, ...
    'ColNameWidth', 0.23, ...
    'FontSize', 13 ...
    );

axis on

plt = plot(MODEL.PreProc.quarterly_temp.imp_indx_dif1_qq , ...
    'Marker', '.', ...
    'MarkerSize', 17, ...
    'LineWidth', 1.25, ...
    'color', [0,0,1]);

%Titulos
title(MODEL.PreProc.quarterly_temp.imp_indx_qq.Comment{1},...
    strcat(dat2char(MODEL.PreProc.quarterly_temp.imp_indx_qq.Start),...
    '-', dat2char(MODEL.PreProc.quarterly_temp.imp_indx_qq.End)));

Sim.scripts.pausaGuarda(...
    fullfile(SavePath,...
    sprintf("%s_short.png",MODEL.PreProc.quarterly.imp_indx_qq.Comment{1})), ...
    'AutoSave', true);

%% Precio de exportaciones

toplot = {'exp_indx_mm', 'exp_indx_dif12_mm'};

for i = 1:length(toplot)
    % Precios de importados en niveles
    set( ...
        gcf, ...
        'defaultaxesfontsize',12, ...
        'Position', [1 42.0182 1417.1 976.73] ...
        );
    
    main_p = uipanel('Units','normalized');
    
    % ----- Panel de gráfica -----
    plot_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8, 1, 0.8], ...
        'BackgroundColor', [1, 1, 1] ...
        );
    
    ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);
    
    % panel
    table_p = uipanel( ...
        main_p, ...
        'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
        'BackgroundColor', [1, 1, 1] ...
        );
    
    data_table = [];
    data_table(:, 1) = MODEL.PreProc.monthly_temp.(toplot{i})(tab_range_mm);
    
    text_Color = [[0 0 1]];
    
    if i == 1
        Sim.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Índice de precios de exportaciones'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
            );
        
    else
        Sim.scripts.plot_data_table( ...
            tab_range_mm, ...
            data_table, ...
            'Parent', table_p, ...
            'SeriesNames', {'Tasa de variación interanual'}, ...
            'TextColor', text_Color, ...
            'ColNameWidth', 0.23, ...
            'FontSize', 13 ...
            );
        
        
    end
    
    axis on
    
    plot(MODEL.PreProc.monthly_temp.(toplot{i}), ...
        'Marker', '.', ...
        'MarkerSize', 17, ...
        'LineWidth', 1.25, ...
        'color', [0,0,1]);
    
    %Titulos
    title(MODEL.PreProc.monthly_temp.(toplot{i}).Comment{1},...
        strcat(dat2char(MODEL.PreProc.monthly_temp.(toplot{i}).Start),...
        '-',dat2char(MODEL.PreProc.monthly_temp.(toplot{i}).End)));
    
    Sim.scripts.pausaGuarda(...
        fullfile('plots',...
        MODEL.CORR_DATE, MODEL.CORR_VER,...
        'PreProcessing',...
        sprintf("%s_short.png",MODEL.PreProc.monthly.(toplot{i}).Comment{1})), ...
        'AutoSave', true);
end

% tasa de intertrimestral anualizada
set( ...
    gcf, ...
    'defaultaxesfontsize',12, ...
    'Position', [1 42.0182 1417.1 976.73] ...
    );

main_p = uipanel('Units','normalized');

% ----- Panel de gráfica -----
plot_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8, 1, 0.8], ...
    'BackgroundColor', [1, 1, 1] ...
    );

ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

% panel
table_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
    'BackgroundColor', [1, 1, 1] ...
    );

data_table = [];
data_table(:, 1) = MODEL.PreProc.quarterly_temp.exp_indx_dif1_qq(tab_range-12);

text_Color = [[0 0 1]];


Sim.scripts.plot_data_table( ...
    tab_range-12, ...
    data_table, ...
    'Parent', table_p, ...
    'SeriesNames', {'Tasa de variación intertrimestral'}, ...
    'TextColor', text_Color, ...
    'ColNameWidth', 0.23, ...
    'FontSize', 13 ...
    );

axis on

plt = plot(MODEL.PreProc.quarterly_temp.exp_indx_dif1_qq, ...
    'Marker', '.', ...
    'MarkerSize', 17, ...
    'LineWidth', 1.25, ...
    'color', [0,0,1]);

%Titulos
title(MODEL.PreProc.quarterly_temp.exp_indx_qq.Comment{1},...
    strcat(dat2char(MODEL.PreProc.quarterly_temp.exp_indx_qq.Start),...
    '-', dat2char(MODEL.PreProc.quarterly_temp.exp_indx_qq.End)));

Sim.scripts.pausaGuarda(...
    fullfile(SavePath,...
    sprintf("%s_short.png",MODEL.PreProc.quarterly_temp.exp_indx_qq.Comment{1})), ...
    'AutoSave', true);


%% Exportaciones e importaciones (juntos)

set( ...
    gcf, ...
    'defaultaxesfontsize',12, ...
    'Position', [1 42.0182 1117.1 776.73] ...
    );


main_p = uipanel('Units','normalized');

% ----- Panel de gráfica -----
plot_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8, 1, 0.8], ...
    'BackgroundColor', [1, 1, 1] ...
    );

ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);


% panel
table_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
    'BackgroundColor', [1, 1, 1] ...
    );

data_table = [];
data_table(:, 1) = MODEL.PreProc.monthly_temp.imp_indx_mm(tab_range_mm);
data_table(:, 2) = MODEL.PreProc.monthly_temp.exp_indx_mm(tab_range_mm);
text_Color = [[0 0 0]; [0 0.498 0]];


Sim.scripts.plot_data_table( ...
    tab_range_mm, ...
    data_table, ...
    'Parent', table_p, ...
    'SeriesNames', {'Índice de Precios de Importaciones',...
    'Índice de Precios de Exportaciones'}, ...
    'TextColor', text_Color, ...
    'ColNameWidth', 0.23, ...
    'FontSize', 11 ...
    );

axis on

plt = plot(...
    [MODEL.PreProc.monthly_temp.imp_indx_mm, MODEL.PreProc.monthly_temp.exp_indx_mm], ...
    'LineWidth', 1.25 ...
    );

% Colores
% importaciones
set(plt(1), 'color', [0 0 0], 'LineWidth', 1.25, 'Marker', '.', 'MarkerSize', 12);
% exportaciones
set(plt(2), 'color', [0 0.498 0],'LineWidth', 1.25, 'Marker', '.', 'MarkerSize', 12);

% leyenda
legend({'Índice de Precios de importaciones',...
    'Índice de Precios de exportaciones'}, 'Location','best');

%Titulos
title('Índices de precios',...
    {'Importaciones y exportaciones EEUU',...
    strcat(dat2char(MODEL.PreProc.monthly_temp.imp_indx_mm.Start),...
    '-',dat2char(MODEL.PreProc.monthly_temp.imp_indx_mm.End))},...
    'FontSiz', 10);

%Guardamos la gráfica
Sim.scripts.pausaGuarda(...
    fullfile(SavePath,...
    sprintf("%s_short.png",'imp_exp_indx')), ...
    'AutoSave', true ...
    );

%% tasas de varaicón interanual de importaciones y exportaciones (juntos)
figure;
set( ...
    gcf, ...
    'defaultaxesfontsize',12, ...
    'Position', [1 42.0182 1117.1 776.73] ...
    );


main_p = uipanel('Units','normalized');

% ----- Panel de gráfica -----
plot_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8, 1, 0.8], ...
    'BackgroundColor', [1, 1, 1] ...
    );

ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

% panel
table_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
    'BackgroundColor', [1, 1, 1] ...
    );

data_table = [];
data_table(:, 1) = MODEL.PreProc.monthly_temp.imp_indx_dif12_mm(tab_range_mm);
data_table(:, 2) = MODEL.PreProc.monthly_temp.exp_indx_dif12_mm(tab_range_mm);
text_Color = [[0 0 0]; [0 0.498 0]];


Sim.scripts.plot_data_table( ...
    tab_range_mm, ...
    data_table, ...
    'Parent', table_p, ...
    'SeriesNames', {'Precios de Importaciones', 'Precios de Exportaciones'}, ...
    'TextColor', text_Color, ...
    'ColNameWidth', 0.23, ...
    'FontSize', 11 ...
    )

plt = plot(...
    [MODEL.PreProc.monthly_temp.imp_indx_dif12_mm, MODEL.PreProc.monthly_temp.exp_indx_dif12_mm], ...
    'LineWidth', 1.25 ...
    );

zeroline();


% Colores
% importaciones
set(plt(1), 'color', [0 0 0], 'LineWidth', 1.25, 'Marker', '.', 'MarkerSize', 12);
% exportaciones
set(plt(2), 'color', [0 0.498 0],'LineWidth', 1.25, 'Marker', '.', 'MarkerSize', 12);

% leyenda
legend({'Precios de importaciones', 'Precios de exportaciones'}, 'Location','best');

%Titulos
title('Tasas de variación interanual',...
    {'Precios de Importaciones y Exportaciones EEUU',...
    strcat(dat2char(MODEL.PreProc.monthly_temp.imp_indx_dif12_mm.Start),...
    '-',dat2char(MODEL.PreProc.monthly_temp.imp_indx_dif12_mm.End))},...
    'FontSiz', 10);


axis on

% Guardamos la gráfica
Sim.scripts.pausaGuarda(...
    fullfile(SavePath,...
    'imp_exp_d12_short.png'), ...
    'AutoSave', true);

%% tasas de varaicón intertrimestral anualizada de importaciones y exportaciones (juntos)
figure;
set( ...
    gcf, ...
    'defaultaxesfontsize',12, ...
    'Position', [1 42.0182 1117.1 776.73] ...
    );


main_p = uipanel('Units','normalized');

% ----- Panel de gráfica -----
plot_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8, 1, 0.8], ...
    'BackgroundColor', [1, 1, 1] ...
    );

ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);

% panel
table_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
    'BackgroundColor', [1, 1, 1] ...
    );

data_table = [];
data_table(:, 1) = MODEL.PreProc.quarterly_temp.imp_indx_dif1_qq(tab_range-12);
data_table(:, 2) = MODEL.PreProc.quarterly_temp.exp_indx_dif1_qq(tab_range-12);
text_Color = [[0 0 0]; [0 0.498 0]];


Sim.scripts.plot_data_table( ...
    tab_range-12, ...
    data_table, ...
    'Parent', table_p, ...
    'SeriesNames', {'Precios de Importaciones', 'Precios de Exportaciones'}, ...
    'TextColor', text_Color, ...
    'ColNameWidth', 0.23, ...
    'FontSize', 11 ...
    );

plt = plot(...
    [MODEL.PreProc.quarterly_temp.imp_indx_dif1_qq, MODEL.PreProc.quarterly_temp.exp_indx_dif1_qq], ...
    'LineWidth', 1.25 ...
    );

zeroline();


% Colores
% importaciones
set(plt(1), 'color', [0 0 0], 'LineWidth', 1.25, 'Marker', '.', 'MarkerSize', 12);
% exportaciones
set(plt(2), 'color', [0 0.498 0],'LineWidth', 1.25, 'Marker', '.', 'MarkerSize', 12);

% leyenda
legend({'Precios de importaciones', 'Precios de exportaciones'}, 'Location','best');

%Titulos
title('Tasas de variación intertrimestral anualizada',...
    {'Precios de Importaciones y Exportaciones EEUU',...
    strcat(dat2char(MODEL.PreProc.quarterly_temp.exp_indx_dif1_qq.Start),...
    '-',dat2char(MODEL.PreProc.quarterly_temp.exp_indx_dif1_qq.End))},...
    'FontSiz', 10);


axis on

% Guardamos la gráfica
Sim.scripts.pausaGuarda(...
    fullfile(SavePath,...
    'imp_exp_t_short.png'), ...
    'AutoSave', true);

%% Evolución alpha
set( ...
    gcf, ...
    'defaultaxesfontsize',12, ...
    'Position', [1 42.0182 1117.1 776.73] ...
    );


main_p = uipanel('Units','normalized');

% ----- Panel de gráfica -----
plot_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8, 1, 0.8], ...
    'BackgroundColor', [1, 1, 1] ...
    );

ax = axes(plot_p, 'Units','normalized' ,'Position', [0.1 0.1 0.85 0.8]);


plt = plot(MODEL.PreProc.monthly_temp.a_prom_mm.Start:MODEL.PreProc.monthly_temp.a_prom_mm.End,...
    [MODEL.PreProc.monthly_temp.a_mm, MODEL.PreProc.monthly_temp.a_prom_mm], ...
    'LineWidth', 1.25 ...
    );

% Colores
% mes con mes
set(plt(1), 'color', [0 0 0], 'LineWidth', 1.25);
% promedio movil 12 meses
set(plt(2), 'color', [0 0.498 0],'LineWidth', 1.25, 'Marker', '.', 'MarkerSize', 12);

% leyenda
legend({'Evolución mensual', 'Promedio Movil (12 meses)'}, 'Location','best');

%Titulos
title('Importancia de EEUU en importaciones de GT',...
    strcat(dat2char(MODEL.PreProc.monthly_temp.a_prom_mm.Start),...
    '-',dat2char(MODEL.PreProc.monthly_temp.a_prom_mm.End)))

% panel
table_p = uipanel( ...
    main_p, ...
    'Position', [0, 1 - 0.8 - 0.20, 1, 0.20], ...
    'BackgroundColor', [1, 1, 1] ...
    );

data_table = [];
data_table(:, 1) = MODEL.PreProc.monthly_temp.a_mm(tab_range_mm);
data_table(:, 2) = MODEL.PreProc.monthly_temp.a_prom_mm(tab_range_mm);
text_Color = [[0 0 0]; [0 0.498 0]];


Sim.scripts.plot_data_table( ...
    tab_range_mm, ...
    data_table, ...
    'Parent', table_p, ...
    'SeriesNames', {'Evolución mensual', 'Promedio Movil 12 meses'}, ...
    'TextColor', text_Color, ...
    'ColNameWidth', 0.23, ...
    'FontSize', 11 ...
    );

axis on

Sim.scripts.pausaGuarda(...
    fullfile(SavePath,...
    'alpha_short.png'), ...
    'AutoSave', true);

%%
close all;

