function contributions(MODEL, varargin)
%{
    Descomposición de las contribuciones para cada una de las variables de
    interés. Las constribuciones se construyen a partir de la ecuación que
    define a cada una dentro de la estructura del modelo.

    Variables:
    MCI: Indice de Condiciones Monetarias 
    RMC: Costos Marianels Reales
    IS: Curva IS (Demanda Agregada)
    Phillips: Curva de Phillips (Inflación subyacente (variación
              intertrimestral))
    Regla de Taylor: Tasa de interés lider


__`MODEL`__ [ struct ] -
Debe contener al menos la estructura con los resultados del 
pre-procesamiento de los datos.

* 'StartDate' = {} [ `Cell` ] - Fechas de inicio del plot (Puede ser una o mas).
* 'EndDatePlot' = {} [ `Cell` ] - fechas de fin del plot (pueden ser una o mas).

* 'Esc_add' = {}  [ `Cell` ] - Escenario adicional a plotear. Cell array 
    con dos elementos: (1) Versión o fecha del escenario adicional y (2)
    Base de datos con los datos historicos del corrimiento anterior.

Departamento de Investigaciones Económicas - 2024.
MJGM/JGOR

%}

p = inputParser;
addParameter(p, 'StartDate', {MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20});
addParameter(p, 'EndDatePlot', {MODEL.DATES.pred_end});
addParameter(p, 'SavePath', {});
addParameter(p, 'Esc_add', {}); % libre v0, alterno v1, contrafactual v2...
addParameter(p, 'tab_range', {});

parse(p, varargin{:});
params = p.Results;

%% Limpieza y creación de folders
% Verificación y creación del directorio para las gráficas
if isempty(params.SavePath)
    params.SavePath = fullfile('plots', MODEL.CORR_DATE, params.Esc_add{1}, 'contributions');
end

if ~isfolder(params.SavePath)
    mkdir(params.SavePath)
    mkdir(fullfile(params.SavePath, 'long'))
    mkdir(fullfile(params.SavePath, 'short'))
else
    rmdir(params.SavePath, 's')
    mkdir(params.SavePath)
    mkdir(fullfile(params.SavePath, 'long'))
    mkdir(fullfile(params.SavePath, 'short'))
end

%% Carga de base de datos mes anterior
if strcmp(params.Esc_add{1}, 'v0')   
    full_data_add = params.Esc_add{2};
else
    full_data_add.F_pred = params.Esc_add{2};
    full_data_add.DATES = MODEL.DATES;
end
    
%% Identificador
if strcmp(params.Esc_add{1}, 'v0')   
   params.date_ant = MODEL.CORR_DATE_ANT;
else
   params.date_ant = 'Alterno';
end

%% Producto doméstico
params.leg = {'Constante','Producto externo', 'Precios de importados', 'Tasa externa', 'Inflación no subyacente',...
              'Producto doméstico', 'Base monetaria',...
              'Shock Propio'};

% Paleta de colores
col = distinguishable_colors(length(params.leg)+1, ...
    'b', ...
    @(x) colorspace('RGB->Lab',x));
          
    for rng = params.StartDate
        % Corrimiento actual
        figure;
        set(gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1.6756e+03 825.6000]);
        % Barras
        bar(rng{1}:params.EndDatePlot{1},...
            [(MODEL.F.k5),...
            (MODEL.F.g_1_51*MODEL.F_pred.d4_ln_y_star.shift(-1)    - MODEL.F.g_0_51*MODEL.F_pred.d4_ln_y_star),...
            (MODEL.F.g_1_52*MODEL.F_pred.d4_ln_ipei.shift(-1)      - MODEL.F.g_0_52*MODEL.F_pred.d4_ln_ipei),......
            (MODEL.F.g_1_53*MODEL.F_pred.i_star.shift(-1)          - MODEL.F.g_0_53*MODEL.F_pred.i_star),...,...
            (MODEL.F.g_1_54*MODEL.F_pred.d4_ln_cpi_nosub.shift(-1) - MODEL.F.g_0_54*MODEL.F_pred.d4_ln_cpi_nosub),......
            (MODEL.F.g_1_55*MODEL.F_pred.d4_ln_y.shift(-1)),...
            (MODEL.F.g_1_58*MODEL.F_pred.d4_ln_bm.shift(-1))...
            (MODEL.F_pred.s_d4_ln_y)],...
            'stacked');
        
        hold on

        % Lineas
        plot(rng{1}:params.EndDatePlot{1}, MODEL.F_pred.d4_ln_y,'w','LineWidth',5);
        plot(rng{1}:params.EndDatePlot{1}, MODEL.F_pred.d4_ln_y,'k.-','LineWidth',2, 'MarkerSize', 20);

        
        vline(...
              MODEL.DATES.hist_end,...
              'LineWidth', 1, ...
              'LineStyle', '-.');

        hold off
        
        legend(params.leg, 'Location', 'northeastoutside',...
               'FontSize', 11.5);

        colororder(col);

        if strcmp(params.Esc_add{1}, 'v0')
        title('Producto Doméstico',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1})),...
                'FontSize', 17)

        else
        title({'Producto Doméstico',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1}))},...
                'Corrimiento Libre',...
                'FontSize', 17)
        end
           
        
        grid on

        % Guardamos la gráfica
        if rng{1} == params.StartDate{1}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'long',...
                sprintf("%s_%s.png", 'd4_ln_y', MODEL.CORR_DATE)), ...
                'AutoSave', true);

        elseif rng{1} == params.StartDate{2}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'short',...
                sprintf("%s_%s_short.png", 'd4_ln_y', MODEL.CORR_DATE)), ...
                'AutoSave', true);

        end
        
        % Corrimiento anterior/Escenario
        figure;
        set(gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1.6756e+03 825.6000]);
        % Barras
        bar(rng{1}:params.EndDatePlot{1},...
           [(full_data_add.F.k5),...
            (MODEL.F.g_1_51*full_data_add.F_pred.d4_ln_y_star.shift(-1)    - MODEL.F.g_0_51*full_data_add.F_pred.d4_ln_y_star),...
            (MODEL.F.g_1_52*full_data_add.F_pred.d4_ln_ipei.shift(-1)      - MODEL.F.g_0_52*full_data_add.F_pred.d4_ln_ipei),......
            (MODEL.F.g_1_53*full_data_add.F_pred.i_star.shift(-1)          - MODEL.F.g_0_53*full_data_add.F_pred.i_star),...,...
            (MODEL.F.g_1_54*full_data_add.F_pred.d4_ln_cpi_nosub.shift(-1) - MODEL.F.g_0_54*full_data_add.F_pred.d4_ln_cpi_nosub),......
            (MODEL.F.g_1_55*full_data_add.F_pred.d4_ln_y.shift(-1)),...
            (MODEL.F.g_1_58*full_data_add.F_pred.d4_ln_bm.shift(-1))...
            (full_data_add.F_pred.s_d4_ln_y)],...
            'stacked');
        
        
%          [full_data_add.F.k5,...
%             -full_data_add.F.g_0_51 * full_data_add.F_pred.d4_ln_y_star - full_data_add.F.g_0_52*full_data_add.F_pred.d4_ln_ipei - full_data_add.F.g_0_53*full_data_add.F_pred.i_star,...
%             -full_data_add.F.g_0_54*full_data_add.F_pred.d4_ln_cpi_nosub  full_data_add.F.g_1_51*full_data_add.F_pred.d4_ln_y_star.shift(-1),...
%             full_data_add.F.g_1_52*full_data_add.F_pred.d4_ln_ipei.shift(-1) full_data_add.F.g_1_53*full_data_add.F_pred.i_star.shift(-1),...
%             full_data_add.F.g_1_54*full_data_add.F_pred.d4_ln_cpi_nosub.shift(-1) full_data_add.F.g_1_55*full_data_add.F_pred.d4_ln_y.shift(-1),...
%             full_data_add.F.g_1_58*full_data_add.F_pred.d4_ln_bm.shift(-1) full_data_add.F_pred.s_d4_ln_y]
        
        hold on

        % Lineas
        plot(rng{1}:params.EndDatePlot{1}, full_data_add.F_pred.d4_ln_y,'w','LineWidth',5);
        plot(rng{1}:params.EndDatePlot{1}, full_data_add.F_pred.d4_ln_y,'k.-','LineWidth',2, 'MarkerSize', 20);

        
        vline(...
              full_data_add.DATES.hist_end,...
              'LineWidth', 1, ...
              'LineStyle', '-.');

        hold off
        
        legend(params.leg, 'Location', 'northeastoutside',...
               'FontSize', 11.5);

        colororder(col);

        if strcmp(params.Esc_add{1}, 'v0')
        title('Producto Doméstico',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1})),...
                'FontSize', 17)

        else
        title({'Producto Doméstico',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1}))},...
                'Alterno',...
                'FontSize', 17)
        end
           
        
        grid on

        % Guardamos la gráfica
        if rng{1} == params.StartDate{1}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'long',...
                sprintf("%s_%s.png", 'd4_ln_y', full_data_add.CORR_DATE)), ...
                'AutoSave', true);

        elseif rng{1} == params.StartDate{2}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'short',...
                sprintf("%s_%s_short.png", 'd4_ln_y', full_data_add.CORR_DATE)), ...
                'AutoSave', true);

        end
        
    end

%% Inflación subyacente
params.leg = {'Constante',...1
              'Producto externo',...2
              'Precios de importados',...3
              'Tasa externa',...4
              'Inflación no subyacente',...5
              'Producto doméstico',...6
              'Inflación Subyacente',...7
              'Base monetaria',...8
              'Shock Propio'};%9

% Paleta de colores
col = distinguishable_colors(length(params.leg)+1, ...
    'b', ...
    @(x) colorspace('RGB->Lab',x));
          
    for rng = params.StartDate
        % Corrimiento actual
        figure;
        set(gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1.6756e+03 825.6000]);
        % Barras
        bar(rng{1}:params.EndDatePlot{1},...
            [MODEL.F.k6,...1
             MODEL.F.g_1_61*MODEL.F_pred.d4_ln_y_star.shift(-1) - MODEL.F.g_0_61*MODEL.F_pred.d4_ln_y_star,...2
             MODEL.F.g_1_62*MODEL.F_pred.d4_ln_ipei.shift(-1)   - MODEL.F.g_0_62*MODEL.F_pred.d4_ln_ipei,...3
             MODEL.F.g_1_63*MODEL.F_pred.i_star.shift(-1)       - MODEL.F.g_0_63*MODEL.F_pred.i_star,...4
             MODEL.F.g_1_64*MODEL.F_pred.d4_ln_cpi_nosub.shift(-1) - MODEL.F.g_0_64*MODEL.F_pred.d4_ln_cpi_nosub,...5
             MODEL.F.g_1_65*MODEL.F_pred.d4_ln_y.shift(-1)      - MODEL.F.g_0_65*MODEL.F_pred.d4_ln_y,...6
             MODEL.F.g_1_66*MODEL.F_pred.d4_ln_cpi_sub.shift(-1),...7
             MODEL.F.g_1_68*MODEL.F_pred.d4_ln_bm.shift(-1),... 8
             MODEL.F_pred.s_d4_ln_cpi_sub],...9
            'stacked');
        
        hold on

        % Lineas
        plot(rng{1}:params.EndDatePlot{1}, MODEL.F_pred.d4_ln_cpi_sub,'w','LineWidth',5);
        plot(rng{1}:params.EndDatePlot{1}, MODEL.F_pred.d4_ln_cpi_sub,'k.-','LineWidth',2, 'MarkerSize', 20);

        
        vline(...
              MODEL.DATES.hist_end,...
              'LineWidth', 1, ...
              'LineStyle', '-.');

        hold off
        
        legend(params.leg, 'Location', 'northeastoutside',...
               'FontSize', 11.5);

        colororder(col);

        if strcmp(params.Esc_add{1}, 'v0')
        title('Inflación subyacente',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1})),...
                'FontSize', 17)

        else
        title({'Inflación subyacente',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1}))},...
                'Corrimiento Libre',...
                'FontSize', 17)
        end
           
        
        grid on

        % Guardamos la gráfica
        if rng{1} == params.StartDate{1}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'long',...
                sprintf("%s_%s.png", 'd4_ln_cpi_sub', MODEL.CORR_DATE)), ...
                'AutoSave', true);

        elseif rng{1} == params.StartDate{2}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'short',...
                sprintf("%s_%s_short.png", 'd4_ln_cpi_sub', MODEL.CORR_DATE)), ...
                'AutoSave', true);
        end
        
        % Corrimiento anterior/Escenario
        figure;
        set(gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1.6756e+03 825.6000]);
        % Barras
        bar(rng{1}:params.EndDatePlot{1},...
            [MODEL.F.k6,...1
             (MODEL.F.g_1_61*full_data_add.F_pred.d4_ln_y_star.shift(-1) - MODEL.F.g_0_61*full_data_add.F_pred.d4_ln_y_star),...2
             (MODEL.F.g_1_62*full_data_add.F_pred.d4_ln_ipei.shift(-1)   - MODEL.F.g_0_62*full_data_add.F_pred.d4_ln_ipei),...3
             (MODEL.F.g_1_63*full_data_add.F_pred.i_star.shift(-1)       - MODEL.F.g_0_63*full_data_add.F_pred.i_star),...4
             (MODEL.F.g_1_64*full_data_add.F_pred.d4_ln_cpi_nosub.shift(-1) - MODEL.F.g_0_64*full_data_add.F_pred.d4_ln_cpi_nosub),...5
             (MODEL.F.g_1_65*full_data_add.F_pred.d4_ln_y.shift(-1)      -MODEL.F.g_0_65*full_data_add.F_pred.d4_ln_y),...6
             (MODEL.F.g_1_66*full_data_add.F_pred.d4_ln_cpi_sub.shift(-1)),...7
             (MODEL.F.g_1_68*full_data_add.F_pred.d4_ln_bm.shift(-1)),... 8
             full_data_add.F_pred.s_d4_ln_cpi_sub],...9
            'stacked');
        
        hold on

        % Lineas
        plot(rng{1}:params.EndDatePlot{1}, full_data_add.F_pred.d4_ln_cpi_sub,'w','LineWidth',5);
        plot(rng{1}:params.EndDatePlot{1}, full_data_add.F_pred.d4_ln_cpi_sub,'k.-','LineWidth',2, 'MarkerSize', 20);

        
        vline(...
              full_data_add.DATES.hist_end,...
              'LineWidth', 1, ...
              'LineStyle', '-.');

        hold off
        
        legend(params.leg, 'Location', 'northeastoutside',...
               'FontSize', 11.5);

        colororder(col);

        if strcmp(params.Esc_add{1}, 'v0')
        title('Inflación subyacente',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1})),...
                'FontSize', 17)

        else
        title({'Inflación subyacente',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1}))},...
                'Alterno',...
                'FontSize', 17)
        end
           
        
        grid on

        % Guardamos la gráfica
        if rng{1} == params.StartDate{1}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'long',...
                sprintf("%s_%s.png", 'd4_ln_cpi_sub', full_data_add.CORR_DATE)), ...
                'AutoSave', true);

        elseif rng{1} == params.StartDate{2}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'short',...
                sprintf("%s_%s_short.png", 'd4_ln_cpi_sub', full_data_add.CORR_DATE)), ...
                'AutoSave', true);

        end
        
    end

%% Base Monetaria
params.leg = {'Constante',...1
              'Producto externo',...2
              'Precios de importados',...3
              'Tasa externa',...4
              'Inflación no subyacente',...5
              'Producto doméstico',...6
              'Inflación subyacente',...7
              'Tipo de cambio nominal',...8
              'Base Monetaria',...9
              'Tasa de Interés',...10              
              'Shock Propio'};%11

% Paleta de colores
col = distinguishable_colors(length(params.leg)+1, ...
    'b', ...
    @(x) colorspace('RGB->Lab',x));
          
    for rng = params.StartDate
        % Corrimiento actual
        figure;
        set(gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1.6756e+03 825.6000]);
        % Barras
        bar(rng{1}:params.EndDatePlot{1},...
            [MODEL.F.k8,...
             (MODEL.F.g_1_81*MODEL.F_pred.d4_ln_y_star.shift(-1) - MODEL.F.g_0_81*MODEL.F_pred.d4_ln_y_star),...
             (MODEL.F.g_1_82*MODEL.F_pred.d4_ln_ipei.shift(-1)   - MODEL.F.g_0_82*MODEL.F_pred.d4_ln_ipei),...
             (MODEL.F.g_1_83*MODEL.F_pred.i_star.shift(-1)       - MODEL.F.g_0_83*MODEL.F_pred.i_star),...
             (MODEL.F.g_1_84*MODEL.F_pred.d4_ln_cpi_nosub.shift(-1) - MODEL.F.g_0_84*MODEL.F_pred.d4_ln_cpi_nosub),...
             (MODEL.F.g_1_85*MODEL.F_pred.d4_ln_y.shift(-1)         - MODEL.F.g_0_85*MODEL.F_pred.d4_ln_y),...
             (MODEL.F.g_1_86*MODEL.F_pred.d4_ln_cpi_sub.shift(-1)   - MODEL.F.g_0_86*MODEL.F_pred.d4_ln_cpi_sub),...
             (MODEL.F.g_1_87*MODEL.F_pred.d4_ln_s.shift(-1)         - MODEL.F.g_0_87*MODEL.F_pred.d4_ln_s ),...
             (MODEL.F.g_1_88*MODEL.F_pred.d4_ln_bm.shift(-1)),... 
             (MODEL.F.g_1_89*MODEL.F_pred.i.shift(-1)),...
              MODEL.F_pred.s_i],...
            'stacked');
        
        hold on

        % Lineas
        plot(rng{1}:params.EndDatePlot{1}, MODEL.F_pred.d4_ln_bm,'w','LineWidth',5);
        plot(rng{1}:params.EndDatePlot{1}, MODEL.F_pred.d4_ln_bm,'k.-','LineWidth',2, 'MarkerSize', 20);

        
        vline(...
              MODEL.DATES.hist_end,...
              'LineWidth', 1, ...
              'LineStyle', '-.');

        hold off
        
        legend(params.leg, 'Location', 'northeastoutside',...
               'FontSize', 11.5);

        colororder(col);

        if strcmp(params.Esc_add{1}, 'v0')
        title('Base Monetaria',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1})),...
                'FontSize', 17)

        else
        title({'Base Monetaria',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1}))},...
                'Corrimiento Libre',...
                'FontSize', 17)
        end
           
        
        grid on

        % Guardamos la gráfica
        if rng{1} == params.StartDate{1}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'long',...
                sprintf("%s_%s.png", 'd4_ln_bm', MODEL.CORR_DATE)), ...
                'AutoSave', true);

        elseif rng{1} == params.StartDate{2}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'short',...
                sprintf("%s_%s_short.png", 'd4_ln_bm', MODEL.CORR_DATE)), ...
                'AutoSave', true);
        end
        
        % Corrimiento anterior/Escenario
        figure;
        set(gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1.6756e+03 825.6000]);
        % Barras
        bar(rng{1}:params.EndDatePlot{1},...
            [MODEL.F.k8,...
             (MODEL.F.g_1_81*full_data_add.F_pred.d4_ln_y_star.shift(-1) - MODEL.F.g_0_81*full_data_add.F_pred.d4_ln_y_star),...
             (MODEL.F.g_1_82*full_data_add.F_pred.d4_ln_ipei.shift(-1)   - MODEL.F.g_0_82*full_data_add.F_pred.d4_ln_ipei),...
             (MODEL.F.g_1_83*full_data_add.F_pred.i_star.shift(-1)       - MODEL.F.g_0_83*full_data_add.F_pred.i_star),...
             (MODEL.F.g_1_84*full_data_add.F_pred.d4_ln_cpi_nosub.shift(-1) - MODEL.F.g_0_84*full_data_add.F_pred.d4_ln_cpi_nosub),...
             (MODEL.F.g_1_85*full_data_add.F_pred.d4_ln_y.shift(-1)         - MODEL.F.g_0_85*full_data_add.F_pred.d4_ln_y),...
             (MODEL.F.g_1_86*full_data_add.F_pred.d4_ln_cpi_sub.shift(-1)   - MODEL.F.g_0_86*full_data_add.F_pred.d4_ln_cpi_sub),...
             (MODEL.F.g_1_87*full_data_add.F_pred.d4_ln_s.shift(-1)         - MODEL.F.g_0_87*full_data_add.F_pred.d4_ln_s ),...
             (MODEL.F.g_1_88*full_data_add.F_pred.d4_ln_bm.shift(-1)),... 
             (MODEL.F.g_1_89*full_data_add.F_pred.i.shift(-1)),...
              full_data_add.F_pred.s_i],...
            'stacked');
        
        hold on

        % Lineas
        plot(rng{1}:params.EndDatePlot{1}, full_data_add.F_pred.d4_ln_bm,'w','LineWidth',5);
        plot(rng{1}:params.EndDatePlot{1}, full_data_add.F_pred.d4_ln_bm,'k.-','LineWidth',2, 'MarkerSize', 20);

        
        vline(...
              full_data_add.DATES.hist_end,...
              'LineWidth', 1, ...
              'LineStyle', '-.');

        hold off
        
        legend(params.leg, 'Location', 'northeastoutside',...
               'FontSize', 11.5);

        colororder(col);

        if strcmp(params.Esc_add{1}, 'v0')
        title('Base Monetaria',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1})),...
                'FontSize', 17)

        else
        title({'Base Monetaria',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1}))},...
                'Alterno',...
                'FontSize', 17)
        end
           
        
        grid on

        % Guardamos la gráfica
        if rng{1} == params.StartDate{1}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'long',...
                sprintf("%s_%s.png", 'd4_ln_bm', full_data_add.CORR_DATE)), ...
                'AutoSave', true);

        elseif rng{1} == params.StartDate{2}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'short',...
                sprintf("%s_%s_short.png", 'd4_ln_bm', full_data_add.CORR_DATE)), ...
                'AutoSave', true);

        end
        
    end

%% Tasa de interés
params.leg = {'Constante',...1
              'Producto externo',...2
              'Precios de importados',...3
              'Tasa externa',...4
              'Inflación no subyacente',...5
              'Producto doméstico',...6
              'Inflación subyacente',...7
              'Tipo de cambio nominal',...8
              'Base Monetaria',...9
              'Tasa de Interés',...10              
              'Shock Propio'};%11

% Paleta de colores
col = distinguishable_colors(length(params.leg)+1, ...
    'b', ...
    @(x) colorspace('RGB->Lab',x));
          
    for rng = params.StartDate
        % Corrimiento actual
        figure;
        set(gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1.6756e+03 825.6000]);
        % Barras
        bar(rng{1}:params.EndDatePlot{1},...
            [MODEL.F.k9,...
             (MODEL.F.g_1_91*MODEL.F_pred.d4_ln_y_star.shift(-1)    - MODEL.F.g_0_91*MODEL.F_pred.d4_ln_y_star),...
             (MODEL.F.g_1_92*MODEL.F_pred.d4_ln_ipei.shift(-1)      - MODEL.F.g_0_92*MODEL.F_pred.d4_ln_ipei ),...
             (MODEL.F.g_1_93*MODEL.F_pred.i_star.shift(-1)          - MODEL.F.g_0_93*MODEL.F_pred.i_star),...
             (MODEL.F.g_1_94*MODEL.F_pred.d4_ln_cpi_nosub.shift(-1) - MODEL.F.g_0_94*MODEL.F_pred.d4_ln_cpi_nosub),...
             (MODEL.F.g_1_95*MODEL.F_pred.d4_ln_y.shift(-1)         - MODEL.F.g_0_95*MODEL.F_pred.d4_ln_y),... 
             (MODEL.F.g_1_96*MODEL.F_pred.d4_ln_cpi_sub.shift(-1)   - MODEL.F.g_0_96*MODEL.F_pred.d4_ln_cpi_sub),...
             (MODEL.F.g_1_97*MODEL.F_pred.d4_ln_s.shift(-1)         - MODEL.F.g_0_97*MODEL.F_pred.d4_ln_s),...
             (MODEL.F.g_1_98*MODEL.F_pred.d4_ln_bm.shift(-1)        - MODEL.F.g_0_98*MODEL.F_pred.d4_ln_bm ),...
             (MODEL.F.g_1_99*MODEL.F_pred.i.shift(-1)),...
              MODEL.F_pred.s_i],...
            'stacked');
        
        hold on

        % Lineas
        plot(rng{1}:params.EndDatePlot{1}, MODEL.F_pred.i,'w','LineWidth',5);
        plot(rng{1}:params.EndDatePlot{1}, MODEL.F_pred.i,'k.-','LineWidth',2, 'MarkerSize', 20);

        
        vline(...
              MODEL.DATES.hist_end,...
              'LineWidth', 1, ...
              'LineStyle', '-.');

        hold off
        
        legend(params.leg, 'Location', 'northeastoutside',...
               'FontSize', 11.5);

        colororder(col);

        if strcmp(params.Esc_add{1}, 'v0')
        title('Tasa de Interés',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1})),...
                'FontSize', 17)

        else
        title({'Tasa de Interés',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1}))},...
                'Corrimiento Libre',...
                'FontSize', 17)
        end
           
        
        grid on

        % Guardamos la gráfica
        if rng{1} == params.StartDate{1}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'long',...
                sprintf("%s_%s.png", 'i', MODEL.CORR_DATE)), ...
                'AutoSave', true);

        elseif rng{1} == params.StartDate{2}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'short',...
                sprintf("%s_%s_short.png", 'i', MODEL.CORR_DATE)), ...
                'AutoSave', true);
        end
        
        % Corrimiento anterior/Escenario
        figure;
        set(gcf, ...
            'defaultaxesfontsize',12, ...
            'Position', [1 42.0182 1.6756e+03 825.6000]);
        % Barras
        bar(rng{1}:params.EndDatePlot{1},...
            [MODEL.F.k9,...
             (MODEL.F.g_1_91*full_data_add.F_pred.d4_ln_y_star.shift(-1)    - MODEL.F.g_0_91*full_data_add.F_pred.d4_ln_y_star),...
             (MODEL.F.g_1_92*full_data_add.F_pred.d4_ln_ipei.shift(-1)      - MODEL.F.g_0_92*full_data_add.F_pred.d4_ln_ipei ),...
             (MODEL.F.g_1_93*full_data_add.F_pred.i_star.shift(-1)          - MODEL.F.g_0_93*full_data_add.F_pred.i_star),...
             (MODEL.F.g_1_94*full_data_add.F_pred.d4_ln_cpi_nosub.shift(-1) - MODEL.F.g_0_94*full_data_add.F_pred.d4_ln_cpi_nosub),...
             (MODEL.F.g_1_95*full_data_add.F_pred.d4_ln_y.shift(-1)         - MODEL.F.g_0_95*full_data_add.F_pred.d4_ln_y),... 
             (MODEL.F.g_1_96*full_data_add.F_pred.d4_ln_cpi_sub.shift(-1)   - MODEL.F.g_0_96*full_data_add.F_pred.d4_ln_cpi_sub),...
             (MODEL.F.g_1_97*full_data_add.F_pred.d4_ln_s.shift(-1)         - MODEL.F.g_0_97*full_data_add.F_pred.d4_ln_s),...
             (MODEL.F.g_1_98*full_data_add.F_pred.d4_ln_bm.shift(-1)        - MODEL.F.g_0_98*full_data_add.F_pred.d4_ln_bm ),...
             (MODEL.F.g_1_99*full_data_add.F_pred.i.shift(-1)),...
              full_data_add.F_pred.s_i],...
            'stacked');
        
        hold on

        % Lineas
        plot(rng{1}:params.EndDatePlot{1}, full_data_add.F_pred.i,'w','LineWidth',5);
        plot(rng{1}:params.EndDatePlot{1}, full_data_add.F_pred.i,'k.-','LineWidth',2, 'MarkerSize', 20);

        
        vline(...
              full_data_add.DATES.hist_end,...
              'LineWidth', 1, ...
              'LineStyle', '-.');

        hold off
        
        legend(params.leg, 'Location', 'northeastoutside',...
               'FontSize', 11.5);

        colororder(col);

        if strcmp(params.Esc_add{1}, 'v0')
        title('Tasa de Interés',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1})),...
                'FontSize', 17)

        else
        title({'Tasa de Interés',...
            strcat(dat2char(rng{1}),...
                '-',dat2char(params.EndDatePlot{1}))},...
                'Alterno',...
                'FontSize', 17)
        end
           
        
        grid on

        % Guardamos la gráfica
        if rng{1} == params.StartDate{1}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'long',...
                sprintf("%s_%s.png", 'i', full_data_add.CORR_DATE)), ...
                'AutoSave', true);

        elseif rng{1} == params.StartDate{2}
                SimTools.scripts.pausaGuarda(...
                fullfile(params.SavePath, 'short',...
                sprintf("%s_%s_short.png", 'i', full_data_add.CORR_DATE)), ...
                'AutoSave', true);

        end
        
    end
    
end